export const SET_DAY_SCHEDULE_COMPLETIONS = 'SET_DAY_SCHEDULE_COMPLETIONS';
export const SET_DAY_SCHEDULE_SCHEDULED = 'SET_DAY_SCHEDULE_SCHEDULED';
export const ADD_DAY_SCHEDULE_COMPLETION = 'ADD_DAY_SCHEDULE_COMPLETION';
export const RESET_DAY_SCHEDULE_COMPLETION = 'RESET_DAY_SCHEDULE_COMPLETION';
export const SET_WEEK_SCHEDULE_COMPLETIONS = 'SET_WEEK_SCHEDULE_COMPLETIONS';
export const SET_MONTH_SCHEDULE_COMPLETIONS = 'SET_MONTH_SCHEDULE_COMPLETIONS';
