export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_OAUTH_CREDENTIALS = 'SET_OAUTH_CREDENTIALS';
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const APPLE_SIGN_IN_START = 'APPLE_SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export default {
  SET_CURRENT_USER,
  SET_OAUTH_CREDENTIALS,
  GOOGLE_SIGN_IN_START,
  APPLE_SIGN_IN_START,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILURE,
  SIGN_OUT_START,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_FAILURE,
  SIGN_UP_START,
  SIGN_UP_FAILURE,
};
